import * as mockApi from './mockApi'
import * as realApi from './realApi'

const useMock = (import.meta.env.VITE_USE_MOCK_API ?? 'true') !== 'false'
const api = useMock ? mockApi : realApi

const pick = <T extends keyof typeof mockApi>(key: T) => {
  const realFn = (api as any)[key]
  if (typeof realFn === 'function') return realFn
  return (mockApi as any)[key]
}

export const getPopularListings = pick('getPopularListings')
export const getRecommendedListings = pick('getRecommendedListings')
export const searchListings = pick('searchListings')
export const searchListingsV2 = pick('searchListingsV2')
export const getListingById = pick('getListingById')
export const getListingFacilities = pick('getListingFacilities')
export const getListingReviews = pick('getListingReviews')
export const updateListingLocation = pick('updateListingLocation')
export const resetListingLocation = pick('resetListingLocation')
export const geocodeLocation = pick('geocodeLocation')
export const suggestLocations = pick('suggestLocations')
export const suggestSearch = pick('suggestSearch')
export const getFavorites = pick('getFavorites')
export const getBookings = pick('getBookings')
export const getLandlordListings = pick('getLandlordListings')
export const createListing = pick('createListing')
export const updateListing = pick('updateListing')
export const applyToListing = pick('applyToListing')
export const getApplicationsForSeeker = pick('getApplicationsForSeeker')
export const getApplicationsForLandlord = pick('getApplicationsForLandlord')
export const updateApplicationStatus = pick('updateApplicationStatus')
export const getConversations = pick('getConversations')
export const getConversationForListing = pick('getConversationForListing')
export const getConversationById = pick('getConversationById')
export const getMessages = pick('getMessages')
export const getMessagesForListing = pick('getMessagesForListing')
export const sendMessageToListing = pick('sendMessageToListing')
export const sendMessageToConversation = pick('sendMessageToConversation')
export const markConversationRead = pick('markConversationRead')
export const getOrCreateConversationForApplication = pick('getOrCreateConversationForApplication')
export const getPublicProfile = pick('getPublicProfile')
export const leaveRating = pick('leaveRating')
export const getUserRatings = pick('getUserRatings')
export const reportRating = pick('reportRating')
export const getAdminRatings = pick('getAdminRatings')
export const deleteAdminRating = pick('deleteAdminRating')
export const flagUserSuspicious = pick('flagUserSuspicious')
export const getAdminReports = pick('getAdminReports')
export const getAdminReport = pick('getAdminReport')
export const updateAdminReport = pick('updateAdminReport')
export const getAdminKpiSummary = pick('getAdminKpiSummary')
export const getAdminKpiConversion = pick('getAdminKpiConversion')
export const getAdminKpiTrends = pick('getAdminKpiTrends')
export const startImpersonation = pick('startImpersonation')
export const stopImpersonation = pick('stopImpersonation')
export const publishListing = pick('publishListing')
export const unpublishListing = pick('unpublishListing')
export const archiveListing = pick('archiveListing')
export const restoreListing = pick('restoreListing')
export const markListingRented = pick('markListingRented')
export const markListingAvailable = pick('markListingAvailable')
export const getViewingSlots = pick('getViewingSlots')
export const createViewingSlot = pick('createViewingSlot')
export const updateViewingSlot = pick('updateViewingSlot')
export const deleteViewingSlot = pick('deleteViewingSlot')
export const requestViewingSlot = pick('requestViewingSlot')
export const getViewingRequestsForSeeker = pick('getViewingRequestsForSeeker')
export const getViewingRequestsForLandlord = pick('getViewingRequestsForLandlord')
export const confirmViewingRequest = pick('confirmViewingRequest')
export const rejectViewingRequest = pick('rejectViewingRequest')
export const cancelViewingRequest = pick('cancelViewingRequest')
export const downloadViewingRequestIcs = pick('downloadViewingRequestIcs')
export const getSavedSearches = pick('getSavedSearches')
export const createSavedSearch = pick('createSavedSearch')
export const updateSavedSearch = pick('updateSavedSearch')
export const deleteSavedSearch = pick('deleteSavedSearch')

export const isMockApi = useMock
